In [2]:
import sys
import numpy as np

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1,2,3,4])

In [5]:
b = np.array([0, .5, 1, 1.5, 2])

In [6]:
a[0], a[1]

(1, 2)

In [7]:
a[0:]

array([1, 2, 3, 4])

In [8]:
a[1:3]

array([2, 3])

In [9]:
a[1:-1]

array([2, 3])

In [10]:
a[::2]

array([1, 3])

In [11]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [12]:
b[[0,2,-1]]

array([0., 1., 2.])

## Array types

In [13]:
a

array([1, 2, 3, 4])

In [14]:
a.dtype

dtype('int64')

In [15]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [16]:
b.dtype

dtype('float64')

In [19]:
np.array([1,2,3,4], dtype=float)

array([1., 2., 3., 4.])

In [20]:
np.array([1,2,3,4], dtype=int)

array([1, 2, 3, 4])

In [21]:
c = np.array(['a','b','c'])

In [22]:
c.dtype

dtype('<U1')

In [23]:
d = np.array([{'a':1}, sys])

In [24]:
d.dtype

dtype('O')

## Dimensions and shape

In [25]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [26]:
a.shape

(4,)

In [28]:
a.ndim

1

In [29]:
A.size

6

In [30]:
B = np.array([
    [
        [12,11,10],
        [9,8,7]
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [31]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [32]:
B.shape

(2, 2, 3)

In [34]:
B.ndim

3

In [35]:
B.size

12

In [37]:
c = np.array([
    [
        [12,11,10],
        [9,8,7]
    ],
    [
        [6,5,4],
        [0,0,0]
    ]
])

In [38]:
c.dtype

dtype('int64')

In [39]:
c.shape

(2, 2, 3)

## Indexing and Slicing of Matrices

In [40]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [41]:
A[1]

array([4, 5, 6])

In [42]:
A[1][0]

4

In [43]:
A[1,0]

4

In [44]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [46]:
A[:2,2:]

array([[3],
       [6]])

In [47]:
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [48]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
A[1] = np.array([10,10,10])

In [50]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [51]:
A[2]

array([7, 8, 9])

## Broadcasting and Vectorized operations

In [52]:
a = np.arange(4)

In [53]:
a

array([0, 1, 2, 3])

In [54]:
a + 10

array([10, 11, 12, 13])

In [55]:
a.std()

1.118033988749895

In [56]:
a * 10

array([ 0, 10, 20, 30])

In [58]:
a.std()

1.118033988749895

In [59]:
a += 100

In [60]:
a

array([100, 101, 102, 103])

In [63]:
l = [0,1,2,3,4]

In [62]:
[i * 10 for i in l]

[0, 10, 20, 30, 40]

In [64]:
a = np.arange(4)

In [65]:
a

array([0, 1, 2, 3])

## Boolean array

In [77]:
a = np.arange(4)

In [78]:
a

array([0, 1, 2, 3])

In [79]:
a[0], a[-1]

(0, 3)

In [81]:
a[[True, False, False, True]]

array([0, 3])

## API CALLS

In [73]:
key = 'ERgiOkUjJvSFpG3zMeaFYsBmbxrPjtkzf5MmYQHS'

In [68]:
import requests
import json

In [70]:
ean = '7070099420495'
url  = 'https://kassal.app/api/v1/products/ean/'+ ean

In [74]:
headers = {
    "Content-type": "application/json",
    "Authorization": "Bearer " + key
}

In [76]:
response  = requests.get(url, headers = headers)
    
if response.status_code == 200:
    data = response.json()
    print(data)
else:
    print("Request failed with status code:", response.status_code)

{'data': {'ean': '7070099420495', 'products': [{'id': 74094, 'name': 'Crispy Kuler Rosa 6mm 75g Cacas', 'vendor': 'Cacas', 'brand': 'Cacas', 'description': 'Pynt opp dine bakverk med disse lekre crispy kulene fra Cacas. Kulene har et senter av cornflakes og melkesjokolade, belagt med et tynt lag sukker og rosafarge. Disse sprø kulene er godt egnet til å brukes som dekorasjon på kaker og alle slags bakverk, el', 'ingredients': 'Sukker (57%), melkesjokolade (30,6%) [sukker, helmelkpulver, kakaosmør (min 20%), kakaomasse, emulgator (e322( soyalecitin )), naturlig vaniljesmak, kakaopulver (min 32%)], sprø kjerne (11%) [rismel, hvetemel, sukker, maltmel (hvete), hvetegluten, salt], stabilisator (e414, e473), kakaosmør, gelatin (storfe, halal sertifisert), farge (e174, e163), overflatebehandlingsmiddel (e903, e904).', 'url': 'https://meny.no/Varer/bakevarer-og-kjeks/baking/kakepynt/crispy-kuler-7070099420495', 'image': 'https://bilder.ngdata.no/7070099420495/meny/large.jpg', 'store': {'name'